name: server
visiblename: None
is_public: false
maxplayers: 20
address: localhost
port: 11225
slogan: A CG Server
default_privilege_level: 100
default_permissions:
  - cg:chat.lobby.write
  - cg:chat.lobby.read